### ISSUE TITLE
BUG: probably a misuse of variable?

### ISSUE THREAD

**Issue by articism** [cburnette/boxr#13]
https://github.com/cburnette/boxr/blob/master/lib/boxr/files.rb#L96
the 'until file' will always stop, because 'file' is a parameter of the method, which is not nil.
So it seems that this method won't work upon 202.

**Comment by xhocquet** [comment]
@articism Sorry for the super late response! I believe you're right. It seems it will retry and follow redirects until `file` is expected from the request. The parameter should be `file_id` and the first line fixed to resolve this issue. If you'd like to open a PR, that would be great. Otherwise I'll get around to this. Cheers!

**Comment by xhocquet** [comment]
Thanks for the report! Merged the fix: https://github.com/cburnette/boxr/pull/80

**Comment by articism** [comment]
@xhocquet  better late than none ;)
