### ISSUE TITLE
JRuby support

### ISSUE THREAD

**Issue by tehsven** [cburnette/boxr#37]
Since boxr depends on OJ, it can't be used with JRuby because OJ requires native extensions, and JRuby does not support native extensions. https://github.com/jruby/jruby/wiki/C-Extension-Alternatives

**Comment by cburnette** [comment]
Hey Brian, I just release v1.3.0 of Boxr that removed OJ dependency (among other things).

thanks,
Chad

**Comment by cburnette** [comment]
Hey Brian, I just release v1.3.0 of Boxr that removed OJ dependency (among other things).thanks,ChadOn Feb 15, 2017, at 3:48 PM, Brian Stevenson <notifications@github.com> wrote:Since boxr depends on OJ, it can't be used with JRuby because OJ requires native extensions, and JRuby does not support native extensions. https://github.com/jruby/jruby/wiki/C-Extension-Alternatives—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/cburnette/boxr","title":"cburnette/boxr","subtitle":"GitHub repository","main_image_url":"<a href="https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png" class="">https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png</a>","avatar_image_url":"<a href="https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png" class="">https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png</a>","action":{"name":"Open in GitHub","url":"<a href="https://github.com/cburnette/boxr" class="">https://github.com/cburnette/boxr</a>"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"JRuby support (#37)"}],"action":{"name":"View Issue","url":"<a href="https://github.com/cburnette/boxr/issues/37" class="">https://github.com/cburnette/boxr/issues/37</a>"}}}

**Comment by xhocquet** [comment]
Closing since the dependency was removed
