### ISSUE TITLE
client.all_users method retrieves all users even when passing in value to :limit

### ISSUE THREAD

**Issue by Band-Aid** [cburnette/boxr#50]
https://github.com/cburnette/boxr/blob/5e68c8c3640f33d709d4830ce34631864b1f5db5/lib/boxr/users.rb#L23

Shouldn't the below evaluate AND instead of OR ?
`      if offset.nil? || limit.nil?
        users = get_all_with_pagination(uri, query: query, offset: 0, limit: DEFAULT_LIMIT)
      else
`

Also instead of passing in 'nil' to limit and offset, how about passing offset:0, limit:100 ?
This is the default vaule as stated in the dev docs
https://developer.box.com/reference#get-all-users-in-an-enterprise

`
 def all_users(filter_term: nil, fields: [], offset: 0, limit: 100)
`

**Comment by xhocquet** [comment]
Hey @Band-Aid 

Was just looking at your suggestion, and I think I prefer the current implementation. My thoughts:
1. The defaults already exist, they're just abstracted a bit lower in the method and through a [global constant](https://github.com/cburnette/boxr/blob/master/lib/boxr/client.rb#L32)
2. The codebase uses `nil` as a default param to control whether to add it to the queries, so I think maintaining that pattern would make more sense here instead of changing things up.
3. I think the intent of the `||` operator is to make sure the user is explicitly declaring both the offset and the limit. It would be nice not to have to declare a limit if you just want to use the default, but omitting the offset is a clear mistake.

Thanks for the suggestions!

**Comment by xhocquet** [comment]
By the way, feel free to open a pull request so the limit is not required. I would not put it the default in the parameters though.
