### ISSUE TITLE
Download file based on url

### ISSUE THREAD

**Issue by theasteve** [cburnette/boxr#64]
I got the following url `{"field"=>"69028222", "value"=>"https://app.box.com/shared/static/qdvhm7lq9e23548w9XXXXXXXXXXXX.jpg"}`. Currently, Boxr only supports downloading a file by providing the file id. Is there any work around about downloading a file based on the `url` using `client`? 

Something like, `client.download_file_by_url("https://app.box.com/shared/static/XXXXXXXXXXXX.jpg")`

**Comment by xhocquet** [comment]
Hey @theasteve. No, this library does not provide that functionality. That being said, if you already have a static URI to a file, you can use any HTTP client to download it, right? You could even use `curl` through the command line if you want.

Closing since I don't think this is something this library would support.
