### ISSUE TITLE
How to upload file without storing locally first (aka Heroku)

### ISSUE THREAD

**Issue by TrevorHinesley** [cburnette/boxr#8]
Is there a way to extend the functionality of this to allow uploading files without needing a temporary file on disk to send (since that would be the only way that I know of to get a File object)? Heroku doesn't allow dynamic file (temp or permanent) storage on their servers.

Thanks!

**Comment by cburnette** [comment]
Actually, this works fine on Heroku and I have several apps that do just this.  I would like to add the ability to upload from a stream, though.  There are some considerations that make it non-trivial.  Box supports sending a SHA1 hash and also sending the total file size as part of a pre-flight check. Anyway, here is some code that shows how to do this with a tmp file (this is the code that is running in Heroku):

```ruby
def upload
    #http://www.dropzonejs.com/

    uploaded_file = params[:file]
    folder = params[:folder_id]

    temp_file = File.open(Rails.root.join('tmp', uploaded_file.original_filename), 'wb')
    begin
      temp_file.write(uploaded_file.read)
      temp_file.close

      box_user = Box.user_client(session[:box_id])
      box_file = box_user.upload_file(temp_file.path, folder)
    rescue => ex
      puts ex.message
    ensure
      File.delete(temp_file)
    end

    respond_to do |format|
      format.json{ render :json => {} }
    end
  end
```

**Comment by TrevorHinesley** [comment]
The problem with this, is it's extremely unreliable. Heroku can (and will) wipe temp file before it gets uploaded.

**Comment by cburnette** [comment]
It certainly depends on your tolerance level, but I wouldn’t call it ‘extremely’ unreliable.  The filesystem only gets wiped when your dyno is stopped or restarted, and they suggest you can use it as a temporary scratchpad.  But certainly, until you can upload from the in-memory representation there is a small amount of risk. Even with that there is risk because your dyno can get restarted at any time and you’ll lose the in-memory file anyway.

https://devcenter.heroku.com/articles/dynos#ephemeral-filesystem <https://devcenter.heroku.com/articles/dynos#ephemeral-filesystem>

Chad

**Comment by TrevorHinesley** [comment]
For sure, I understand your points. But the reason I say "extremely" unreliable is because if the file gets written to a separate dyno than the one that tries to send it to Box, it won't be able to find it.

**Comment by alzamora** [comment]
It worked for me!
I know it may sound risky but if your transaction requires milliseconds to write a temporal file to be consequently uploaded somewhere else (like in my case google drive) would be a good approach I reckon.
Thanks Chad

**Comment by EByrdS** [comment]
I faced exactly this problem:
In Gemfile:
```ruby
gem 'google-api-client',        '0.9.24'
gem 'data_uri'
```
and running my app in Heroku.

The HTML form that receives the files is in a different server that the one that will upload it using `Google::Apis::DriveV3::DriveService`. The file is sent in the HTTP request in a DataURL format (`data:application/pdf;base64,AdVWSrhssryrtyErSdweYreTqWE...`), which is read using `URI::Data`.

Uploading files using a `Tempfile` or a `File` with the API's command worked locally (Cloud9) but didn't work in Heroku: 
```ruby
tmp = Tempfile.new(name)
tmp.binmode
uri = URI::Data.new(content) # using gem 'data_uri'
tmp.write(uri.data)
metadata = {name: 'file name', parents: [folder_id], description: 'some description'}
drive_file = @drive_service.create_file(metadata, upload_source: tmp.path, fields: 'id')
tmp.unlink
```

The raised error was:
```
--- !ruby/exception:Google::Apis::ClientError
message: Invalid request
cause: 
status_code: 400
header: !ruby/object:Hurley::Header
body: Can not finalize upload.  Current size is 0.  Expected final size is 1634.
```

Our team found out that this was because Heroku deleted the file before Google was able to upload it. The solution was opening the file and providing a block to ensure its lifetime was sufficient for the upload:
```ruby
metadata = {name: 'file name', parents: [folder_id], description: 'some description'}

Tempfile.open(name) do |f|    # this creates a new 'Tempfile' 
  f.binmode
  f.write(URI::Data.new(content) # content is a DataURL string
  drive_file = @drive_service.create_file(metadata, upload_source: f, fields: 'id')
  # Execute code that depends on successful upload
end
```

This approach works on heroku.
